# Base distante
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update

# Logs prod
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
logging.level.root=INFO
logging.level.com.hematrace=INFO
logging.level.org.springframework.web=INFO
logging.level.org.hibernate=ERROR
logging.level.org.springframework.data.repository=ERROR

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:3600000}

# Hibernate options
spring.jpa.properties.hibernate.query.fail_on_pagination_over_collection_fetch=false
spring.jpa.properties.hibernate.query.in_clause_parameter_padding=false
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false